### ISSUE TITLE
Posixlib

### ISSUE THREAD

**Issue by leifo** [leffmann/vbcc-windows#1]
Great packaging, thanks for that! It's very useful also for our toolchain (see my GitHub page). Could you also package vbcc posixlib, so that it is available in libdir?

**Comment by Leffmann** [comment]
I think it would have to be turned into a complete setup in that case.  Currently, it only produces the plain binaries, but I have a complete vbcc-M68K setup with GUI installer here:
http://eab.abime.net/showthread.php?t=83113

How do you use vbcc?  With full configuration files, or just "bare" with minimum headers and libs?  I'm open to good ideas, because ideally I would like to make something better or simpler than the above installer.

**Comment by Leffmann** [comment]
I looked at your web page and saw that you use the toolchain from the installer package, and the current installer has the posix lib included in the `+posix` configuration.  Let me know if it works.

**Comment by leifo** [comment]
Great news! We will definitely need it for the profiling stuff that is not, yet, demoed on the repo. For the moment, the latest builds should work without posix.

**Comment by Leffmann** [comment]
The new version with POSIX and the most recent updates are now on the EAB link above, so I'll close this issue.
